// Copyright 2021 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=ApplyStatus -linecomment"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ApplyPending-0]
	_ = x[ApplySucceeded-1]
	_ = x[ApplySkipped-2]
	_ = x[ApplyFailed-3]
	_ = x[PrunePending-4]
	_ = x[PruneSucceeded-5]
	_ = x[PruneSkipped-6]
	_ = x[PruneFailed-7]
}

const _ApplyStatus_name = "ApplyPendingApplySucceededApplySkippedApplyFailedPrunePendingPruneSucceededPruneSkippedPruneFailed"

var _ApplyStatus_index = [...]uint8{0, 12, 26, 38, 49, 61, 75, 87, 98}

func (i ApplyStatus) String() string {
	if i < 0 || i >= ApplyStatus(len(_ApplyStatus_index)-1) {
		return "ApplyStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ApplyStatus_name[_ApplyStatus_index[i]:_ApplyStatus_index[i+1]]
}
