// Copyright 2021 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=ReconcileStatus -linecomment"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReconcilePending-0]
	_ = x[ReconcileSucceeded-1]
	_ = x[ReconcileSkipped-2]
	_ = x[ReconcileTimeout-3]
	_ = x[ReconcileFailed-4]
}

const _ReconcileStatus_name = "ReconcilePendingReconcileSucceededReconcileSkippedReconcileTimeoutReconcileFailed"

var _ReconcileStatus_index = [...]uint8{0, 16, 34, 50, 66, 81}

func (i ReconcileStatus) String() string {
	if i < 0 || i >= ReconcileStatus(len(_ReconcileStatus_index)-1) {
		return "ReconcileStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReconcileStatus_name[_ReconcileStatus_index[i]:_ReconcileStatus_index[i+1]]
}
