// Copyright 2020 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=ApplyEventType"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ApplyEventResourceUpdate-0]
	_ = x[ApplyEventCompleted-1]
}

const _ApplyEventType_name = "ApplyEventResourceUpdateApplyEventCompleted"

var _ApplyEventType_index = [...]uint8{0, 24, 43}

func (i ApplyEventType) String() string {
	if i < 0 || i >= ApplyEventType(len(_ApplyEventType_index)-1) {
		return "ApplyEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ApplyEventType_name[_ApplyEventType_index[i]:_ApplyEventType_index[i+1]]
}
