// Copyright 2020 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=ApplyEventOperation"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServersideApplied-0]
	_ = x[Created-1]
	_ = x[Unchanged-2]
	_ = x[Configured-3]
	_ = x[Failed-4]
}

const _ApplyEventOperation_name = "ServersideAppliedCreatedUnchangedConfiguredFailed"

var _ApplyEventOperation_index = [...]uint8{0, 17, 24, 33, 43, 49}

func (i ApplyEventOperation) String() string {
	if i < 0 || i >= ApplyEventOperation(len(_ApplyEventOperation_index)-1) {
		return "ApplyEventOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ApplyEventOperation_name[_ApplyEventOperation_index[i]:_ApplyEventOperation_index[i+1]]
}
