// Copyright 2020 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=DeleteEventType"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeleteEventResourceUpdate-0]
	_ = x[DeleteEventCompleted-1]
	_ = x[DeleteEventFailed-2]
}

const _DeleteEventType_name = "DeleteEventResourceUpdateDeleteEventCompletedDeleteEventFailed"

var _DeleteEventType_index = [...]uint8{0, 25, 45, 62}

func (i DeleteEventType) String() string {
	if i < 0 || i >= DeleteEventType(len(_DeleteEventType_index)-1) {
		return "DeleteEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeleteEventType_name[_DeleteEventType_index[i]:_DeleteEventType_index[i+1]]
}
