// Copyright 2020 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=PruneEventOperation"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pruned-0]
	_ = x[PruneSkipped-1]
}

const _PruneEventOperation_name = "PrunedPruneSkipped"

var _PruneEventOperation_index = [...]uint8{0, 6, 18}

func (i PruneEventOperation) String() string {
	if i < 0 || i >= PruneEventOperation(len(_PruneEventOperation_index)-1) {
		return "PruneEventOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PruneEventOperation_name[_PruneEventOperation_index[i]:_PruneEventOperation_index[i+1]]
}
