// Copyright 2020 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=ResourceAction"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ApplyAction-0]
	_ = x[PruneAction-1]
}

const _ResourceAction_name = "ApplyActionPruneAction"

var _ResourceAction_index = [...]uint8{0, 11, 22}

func (i ResourceAction) String() string {
	if i < 0 || i >= ResourceAction(len(_ResourceAction_index)-1) {
		return "ResourceAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResourceAction_name[_ResourceAction_index[i]:_ResourceAction_index[i+1]]
}
