// Copyright 2020 The Kubernetes Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=StatusEventType"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusEventResourceUpdate-0]
	_ = x[StatusEventCompleted-1]
}

const _StatusEventType_name = "StatusEventResourceUpdateStatusEventCompleted"

var _StatusEventType_index = [...]uint8{0, 25, 45}

func (i StatusEventType) String() string {
	if i < 0 || i >= StatusEventType(len(_StatusEventType_index)-1) {
		return "StatusEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusEventType_name[_StatusEventType_index[i]:_StatusEventType_index[i+1]]
}
