// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wiredelete

import (
	"io"
	"sigs.k8s.io/cli-experimental/internal/pkg/clik8s"
	delete2 "sigs.k8s.io/cli-experimental/internal/pkg/delete"
	"sigs.k8s.io/cli-experimental/internal/pkg/util"
	"sigs.k8s.io/cli-experimental/internal/pkg/wirecli/wireconfig"
	"sigs.k8s.io/cli-experimental/internal/pkg/wirecli/wiregit"
	"sigs.k8s.io/cli-experimental/internal/pkg/wirecli/wirek8s"
)

// Injectors from wire.go:

func DoDelete(resourceConfigPath clik8s.ResourceConfigPath, writer io.Writer, args util.Args) (delete2.Result, error) {
	configFlags, err := wirek8s.NewConfigFlags(args)
	if err != nil {
		return delete2.Result{}, err
	}
	config, err := wirek8s.NewRestConfig(configFlags)
	if err != nil {
		return delete2.Result{}, err
	}
	dynamicInterface, err := wirek8s.NewDynamicClient(config)
	if err != nil {
		return delete2.Result{}, err
	}
	restMapper, err := wirek8s.NewRestMapper(config)
	if err != nil {
		return delete2.Result{}, err
	}
	client, err := wirek8s.NewClient(dynamicInterface, restMapper)
	if err != nil {
		return delete2.Result{}, err
	}
	pluginConfig := wireconfig.NewPluginConfig()
	factory := wireconfig.NewResMapFactory(pluginConfig)
	fileSystem := wireconfig.NewFileSystem()
	transformerFactory := wireconfig.NewTransformerFactory()
	kustomizeProvider := wireconfig.NewKustomizeProvider(factory, fileSystem, transformerFactory, pluginConfig)
	resourceConfigs, err := wireconfig.NewResourceConfig(resourceConfigPath, kustomizeProvider)
	if err != nil {
		return delete2.Result{}, err
	}
	repository := wiregit.NewOptionalRepository(resourceConfigPath)
	commitIter := wiregit.NewOptionalCommitIter(repository)
	commit := wiregit.NewOptionalCommit(commitIter)
	deleteDelete := &delete2.Delete{
		DynamicClient: client,
		Out:           writer,
		Resources:     resourceConfigs,
		Commit:        commit,
	}
	result, err := NewDeleteCommandResult(deleteDelete, writer)
	if err != nil {
		return delete2.Result{}, err
	}
	return result, nil
}
