// Code generated by "stringer -type=inventoryIDMatchStatus"; DO NOT EDIT.

package inventory

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Empty-0]
	_ = x[Match-1]
	_ = x[NoMatch-2]
}

const _inventoryIDMatchStatus_name = "EmptyMatchNoMatch"

var _inventoryIDMatchStatus_index = [...]uint8{0, 5, 10, 17}

func (i inventoryIDMatchStatus) String() string {
	if i < 0 || i >= inventoryIDMatchStatus(len(_inventoryIDMatchStatus_index)-1) {
		return "inventoryIDMatchStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _inventoryIDMatchStatus_name[_inventoryIDMatchStatus_index[i]:_inventoryIDMatchStatus_index[i+1]]
}
