// Code generated by "stringer -type=InventoryPolicy"; DO NOT EDIT.

package inventory

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InventoryPolicyMustMatch-0]
	_ = x[AdoptIfNoInventory-1]
	_ = x[AdoptAll-2]
}

const _InventoryPolicy_name = "InventoryPolicyMustMatchAdoptIfNoInventoryAdoptAll"

var _InventoryPolicy_index = [...]uint8{0, 24, 42, 50}

func (i InventoryPolicy) String() string {
	if i < 0 || i >= InventoryPolicy(len(_InventoryPolicy_index)-1) {
		return "InventoryPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _InventoryPolicy_name[_InventoryPolicy_index[i]:_InventoryPolicy_index[i+1]]
}
